[2025-08-02T01:23:55.424+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T01:09:53.940652+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T01:23:55.494+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T01:09:53.940652+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T01:23:55.554+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T01:09:53.940652+00:00 [queued]>
[2025-08-02T01:23:55.576+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T01:09:53.940652+00:00 [queued]>
[2025-08-02T01:23:55.578+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 5
[2025-08-02T01:23:55.616+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 01:09:53.940652+00:00
[2025-08-02T01:23:55.631+0000] {standard_task_runner.py:60} INFO - Started process 1166 to run task
[2025-08-02T01:23:55.642+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T01:09:53.940652+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpa7k_z91h']
[2025-08-02T01:23:55.646+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask load_to_redshift
[2025-08-02T01:23:55.780+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T01:09:53.940652+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T01:23:55.799+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T01:09:53.940652+00:00 [running]> on host f2527419f673
[2025-08-02T01:23:55.995+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T01:09:53.940652+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T01:09:53.940652+00:00'
[2025-08-02T01:23:56.018+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T01:23:56.031+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T01:23:56.032+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T01:23:56.063+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T01:23:56.079+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T01:23:56.080+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T01:23:56.084+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T01:23:58.265+0000] {redshift_data.py:113} INFO - Polling statement f98c33ad-07c9-47e7-97eb-dad76b3e6a7c
[2025-08-02T01:23:58.552+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T01:24:09.226+0000] {redshift_data.py:113} INFO - Polling statement f98c33ad-07c9-47e7-97eb-dad76b3e6a7c
[2025-08-02T01:24:09.403+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement 'f98c33ad-07c9-47e7-97eb-dad76b3e6a7c' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 1, 23, 58, 71000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: conflicting or redundant options',
 'HasResultSet': False,
 'Id': 'f98c33ad-07c9-47e7-97eb-dad76b3e6a7c',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET\n'
                "\t\t\tIAM_ROLE '';\n"
                '        ',
 'RedshiftPid': 1073889566,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '679',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 01:24:09 GMT',
                                      'x-amzn-requestid': 'de9c3dfb-5772-403d-9d4f-fb2155ac2cd5'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'de9c3dfb-5772-403d-9d4f-fb2155ac2cd5',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 1, 23, 58, 467000, tzinfo=tzlocal())}
[2025-08-02T01:24:09.433+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T010953, start_date=20250802T012355, end_date=20250802T012409
[2025-08-02T01:24:09.480+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 91 for task load_to_redshift (Statement 'f98c33ad-07c9-47e7-97eb-dad76b3e6a7c' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 1, 23, 58, 71000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: conflicting or redundant options',
 'HasResultSet': False,
 'Id': 'f98c33ad-07c9-47e7-97eb-dad76b3e6a7c',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET\n'
                "\t\t\tIAM_ROLE '';\n"
                '        ',
 'RedshiftPid': 1073889566,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '679',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 01:24:09 GMT',
                                      'x-amzn-requestid': 'de9c3dfb-5772-403d-9d4f-fb2155ac2cd5'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'de9c3dfb-5772-403d-9d4f-fb2155ac2cd5',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 1, 23, 58, 467000, tzinfo=tzlocal())}; 1166)
[2025-08-02T01:24:09.566+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T01:24:09.611+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
