[2025-08-02T04:18:41.063+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T04:18:41.137+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T04:18:41.179+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [queued]>
[2025-08-02T04:18:41.194+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [queued]>
[2025-08-02T04:18:41.195+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 5
[2025-08-02T04:18:41.218+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 04:05:53.026388+00:00
[2025-08-02T04:18:41.232+0000] {standard_task_runner.py:60} INFO - Started process 3649 to run task
[2025-08-02T04:18:41.240+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T04:05:53.026388+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpw2o2j2mn']
[2025-08-02T04:18:41.242+0000] {standard_task_runner.py:88} INFO - Job 148: Subtask load_to_redshift
[2025-08-02T04:18:41.341+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T04:18:41.365+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [running]> on host f2527419f673
[2025-08-02T04:18:41.510+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T04:05:53.026388+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T04:05:53.026388+00:00'
[2025-08-02T04:18:41.526+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T04:18:41.539+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T04:18:41.540+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T04:18:41.558+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T04:18:41.569+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T04:18:41.570+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T04:18:41.571+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T04:18:43.787+0000] {redshift_data.py:113} INFO - Polling statement c6e4876e-ed33-4ddf-b39c-cb4a53921185
[2025-08-02T04:18:43.972+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T04:18:53.986+0000] {redshift_data.py:113} INFO - Polling statement c6e4876e-ed33-4ddf-b39c-cb4a53921185
[2025-08-02T04:18:54.174+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T04:19:05.276+0000] {redshift_data.py:113} INFO - Polling statement c6e4876e-ed33-4ddf-b39c-cb4a53921185
[2025-08-02T04:19:05.481+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement 'c6e4876e-ed33-4ddf-b39c-cb4a53921185' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 4, 18, 43, 555000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   Unmatched number of columns between table and file. '
          'Table columns: 25, Data columns: 22, File name: '
          'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/6dd739989123489bb43f109069ad0b1e.snappy.parquet\n'
          '  query:     210110\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=19479]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': 'c6e4876e-ed33-4ddf-b39c-cb4a53921185',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073766666,
 'RedshiftQueryId': 210112,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1157',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 04:19:05 GMT',
                                      'x-amzn-requestid': 'e8d9e56c-766a-4b94-8d6a-fd7be3bf16d1'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'e8d9e56c-766a-4b94-8d6a-fd7be3bf16d1',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 4, 19, 1, 493000, tzinfo=tzlocal())}
[2025-08-02T04:19:05.503+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T040553, start_date=20250802T041841, end_date=20250802T041905
[2025-08-02T04:19:05.535+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 148 for task load_to_redshift (Statement 'c6e4876e-ed33-4ddf-b39c-cb4a53921185' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 4, 18, 43, 555000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   Unmatched number of columns between table and file. '
          'Table columns: 25, Data columns: 22, File name: '
          'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/6dd739989123489bb43f109069ad0b1e.snappy.parquet\n'
          '  query:     210110\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=19479]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': 'c6e4876e-ed33-4ddf-b39c-cb4a53921185',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073766666,
 'RedshiftQueryId': 210112,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1157',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 04:19:05 GMT',
                                      'x-amzn-requestid': 'e8d9e56c-766a-4b94-8d6a-fd7be3bf16d1'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'e8d9e56c-766a-4b94-8d6a-fd7be3bf16d1',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 4, 19, 1, 493000, tzinfo=tzlocal())}; 3649)
[2025-08-02T04:19:05.618+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T04:19:05.675+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
