[2025-08-02T18:13:40.786+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T18:13:40.868+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T18:13:40.923+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [queued]>
[2025-08-02T18:13:40.943+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [queued]>
[2025-08-02T18:13:40.945+0000] {taskinstance.py:2170} INFO - Starting attempt 16 of 17
[2025-08-02T18:13:40.980+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 04:05:53.026388+00:00
[2025-08-02T18:13:41.019+0000] {standard_task_runner.py:60} INFO - Started process 357 to run task
[2025-08-02T18:13:41.045+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T04:05:53.026388+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpooj4jpb4']
[2025-08-02T18:13:41.053+0000] {standard_task_runner.py:88} INFO - Job 174: Subtask load_to_redshift
[2025-08-02T18:13:41.272+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T18:13:41.312+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [running]> on host 2f861e5e7e42
[2025-08-02T18:13:41.691+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T04:05:53.026388+00:00' AIRFLOW_CTX_TRY_NUMBER='16' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T04:05:53.026388+00:00'
[2025-08-02T18:13:41.755+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T18:13:41.776+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T18:13:41.785+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T18:13:41.831+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T18:13:41.848+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T18:13:41.849+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T18:13:41.851+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T18:13:44.253+0000] {redshift_data.py:113} INFO - Polling statement dcd6540c-d807-4d53-8f40-64854a0cc368
[2025-08-02T18:13:44.471+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T18:13:54.484+0000] {redshift_data.py:113} INFO - Polling statement dcd6540c-d807-4d53-8f40-64854a0cc368
[2025-08-02T18:13:54.784+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement 'dcd6540c-d807-4d53-8f40-64854a0cc368' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 18, 13, 43, 995000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Cannot COPY into nonexistent table cdr_records',
 'HasResultSet': False,
 'Id': 'dcd6540c-d807-4d53-8f40-64854a0cc368',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073750175,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '675',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 18:13:54 GMT',
                                      'x-amzn-requestid': '1ceb1e92-dae9-4f28-ab92-f4e1acb58ec8'},
                      'HTTPStatusCode': 200,
                      'RequestId': '1ceb1e92-dae9-4f28-ab92-f4e1acb58ec8',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 18, 13, 44, 429000, tzinfo=tzlocal())}
[2025-08-02T18:13:54.799+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T040553, start_date=20250802T181340, end_date=20250802T181354
[2025-08-02T18:13:54.827+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 174 for task load_to_redshift (Statement 'dcd6540c-d807-4d53-8f40-64854a0cc368' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 18, 13, 43, 995000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Cannot COPY into nonexistent table cdr_records',
 'HasResultSet': False,
 'Id': 'dcd6540c-d807-4d53-8f40-64854a0cc368',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073750175,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '675',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 18:13:54 GMT',
                                      'x-amzn-requestid': '1ceb1e92-dae9-4f28-ab92-f4e1acb58ec8'},
                      'HTTPStatusCode': 200,
                      'RequestId': '1ceb1e92-dae9-4f28-ab92-f4e1acb58ec8',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 18, 13, 44, 429000, tzinfo=tzlocal())}; 357)
[2025-08-02T18:13:54.909+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T18:13:54.945+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
