[2025-08-02T18:00:43.893+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T18:01:47.039+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T18:01:47.378+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [queued]>
[2025-08-02T18:01:47.464+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [queued]>
[2025-08-02T18:01:47.466+0000] {taskinstance.py:2170} INFO - Starting attempt 12 of 12
[2025-08-02T18:01:47.635+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 04:05:53.026388+00:00
[2025-08-02T18:01:47.680+0000] {standard_task_runner.py:60} INFO - Started process 189 to run task
[2025-08-02T18:01:47.721+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T04:05:53.026388+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpyxtkevyz']
[2025-08-02T18:01:47.736+0000] {standard_task_runner.py:88} INFO - Job 169: Subtask load_to_redshift
[2025-08-02T18:01:48.434+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T18:01:48.503+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [running]> on host 2f861e5e7e42
[2025-08-02T18:01:50.078+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T04:05:53.026388+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T04:05:53.026388+00:00'
[2025-08-02T18:01:50.273+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T18:01:50.356+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T18:01:50.371+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T18:01:50.595+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T18:01:50.693+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T18:01:50.696+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T18:01:50.707+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T18:01:59.611+0000] {redshift_data.py:113} INFO - Polling statement 2386499d-d982-4d69-a7d1-f53ba4a6e0b8
[2025-08-02T18:01:59.824+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T18:02:09.836+0000] {redshift_data.py:113} INFO - Polling statement 2386499d-d982-4d69-a7d1-f53ba4a6e0b8
[2025-08-02T18:02:10.094+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement '2386499d-d982-4d69-a7d1-f53ba4a6e0b8' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 18, 2, 0, 568000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Cannot COPY into nonexistent table cdr_records',
 'HasResultSet': False,
 'Id': '2386499d-d982-4d69-a7d1-f53ba4a6e0b8',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073782933,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '675',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 18:02:12 GMT',
                                      'x-amzn-requestid': '0d302083-9d5e-4372-9a56-83d9c882f0a5'},
                      'HTTPStatusCode': 200,
                      'RequestId': '0d302083-9d5e-4372-9a56-83d9c882f0a5',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 18, 2, 1, 1000, tzinfo=tzlocal())}
[2025-08-02T18:02:10.137+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T040553, start_date=20250802T180147, end_date=20250802T180210
[2025-08-02T18:02:10.185+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 169 for task load_to_redshift (Statement '2386499d-d982-4d69-a7d1-f53ba4a6e0b8' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 18, 2, 0, 568000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Cannot COPY into nonexistent table cdr_records',
 'HasResultSet': False,
 'Id': '2386499d-d982-4d69-a7d1-f53ba4a6e0b8',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073782933,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '675',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 18:02:12 GMT',
                                      'x-amzn-requestid': '0d302083-9d5e-4372-9a56-83d9c882f0a5'},
                      'HTTPStatusCode': 200,
                      'RequestId': '0d302083-9d5e-4372-9a56-83d9c882f0a5',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 18, 2, 1, 1000, tzinfo=tzlocal())}; 189)
[2025-08-02T18:02:10.308+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T18:02:10.446+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
