[2025-08-04T14:48:12.834+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-07-30T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T14:48:13.041+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-07-30T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T14:48:13.155+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-07-30T00:00:00+00:00 [queued]>
[2025-08-04T14:48:13.195+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-07-30T00:00:00+00:00 [queued]>
[2025-08-04T14:48:13.202+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-04T14:48:13.285+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-07-30 00:00:00+00:00
[2025-08-04T14:48:13.355+0000] {standard_task_runner.py:60} INFO - Started process 735 to run task
[2025-08-04T14:48:13.407+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'scheduled__2025-07-30T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8_08kc76']
[2025-08-04T14:48:13.422+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask load_to_redshift
[2025-08-04T14:48:14.169+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-07-30T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T14:48:14.238+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-07-30T00:00:00+00:00 [running]> on host 9edf237adf6e
[2025-08-04T14:48:15.114+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-30T00:00:00+00:00'
[2025-08-04T14:48:15.205+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T14:48:15.269+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T14:48:15.274+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T14:48:15.570+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-04T14:48:15.626+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-04T14:48:15.632+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T14:48:27.161+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 99, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ExecuteStatement operation: Redshift endpoint is not available.
[2025-08-04T14:48:27.215+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250730T000000, start_date=20250804T144813, end_date=20250804T144827
[2025-08-04T14:48:27.293+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task load_to_redshift (An error occurred (ValidationException) when calling the ExecuteStatement operation: Redshift endpoint is not available.; 735)
[2025-08-04T14:48:27.517+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-04T14:48:27.596+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T16:29:11.558+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-07-30T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T16:29:11.697+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-07-30T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T16:30:16.536+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-07-30T00:00:00+00:00 [queued]>
[2025-08-04T16:30:16.588+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-07-30T00:00:00+00:00 [queued]>
[2025-08-04T16:30:16.596+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-04T16:30:16.719+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-07-30 00:00:00+00:00
[2025-08-04T16:30:16.766+0000] {standard_task_runner.py:60} INFO - Started process 2213 to run task
[2025-08-04T16:30:16.788+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'scheduled__2025-07-30T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxqd4vgro']
[2025-08-04T16:30:16.814+0000] {standard_task_runner.py:88} INFO - Job 90: Subtask load_to_redshift
[2025-08-04T16:30:17.324+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-07-30T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T16:30:17.384+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-07-30T00:00:00+00:00 [running]> on host 9edf237adf6e
[2025-08-04T16:30:18.517+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-30T00:00:00+00:00'
[2025-08-04T16:30:18.603+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T16:30:18.667+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T16:30:18.669+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T16:30:18.802+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-04T16:30:18.834+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-04T16:30:18.837+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T16:30:30.397+0000] {redshift_data.py:113} INFO - Polling statement eb058ed1-2753-4c5c-b86f-be1790a1bffc
[2025-08-04T16:30:30.927+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-04T16:30:40.951+0000] {redshift_data.py:113} INFO - Polling statement eb058ed1-2753-4c5c-b86f-be1790a1bffc
[2025-08-04T16:30:41.267+0000] {redshift_data.py:121} INFO - Processed 0 rows
[2025-08-04T16:30:41.268+0000] {s3_to_redshift.py:197} INFO - COPY command complete...
[2025-08-04T16:30:41.305+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250730T000000, start_date=20250804T163016, end_date=20250804T163041
[2025-08-04T16:30:41.510+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-04T16:30:41.622+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
